### ISSUE TITLE
The result is not good

### ISSUE THREAD

**Issue by linshisong** [AaronJackson/vrn#124]
I upload the 2D image from Bosphorus to generate the 3D face, But the performance does not seems very good.  
![微信图片_20190318092932](https://user-images.githubusercontent.com/23445873/54501470-68799f80-4960-11e9-8b49-6b7bcfea7f68.png)

In addition, I want to get the 3D face just in front of me? As shown below.
![微信图片_20190318093502](https://user-images.githubusercontent.com/23445873/54502239-8517d680-4964-11e9-8682-7ab5b139a5e2.png)
How shuold I modify the code? Thanks

**Comment by AaronJackson** [comment]
Your question is very vague and has no detail. Can you expand?
What is Bosphorus?
Are you using the online demo or running the code yourself?
Is the second image output from our method or something else?
What do you mean by "I want to get the 3D face just in front of me?" ??

**Comment by linshisong** [comment]
I am sorry that I did not express clearly.
Bosphorus is a face database. As shown below. And I use the online demo to generate the OBJ model. The result is not good. 
![bs000_CAU_A22A25_0](https://user-images.githubusercontent.com/23445873/54517166-e27b4a00-499b-11e9-8f9a-f2bf10107683.png)

The second image is the OBJ model that I want to generate, it has only one facet. 
But I use your method, it seems that there are too many facets.  Is there any parameter in your code that controls the number of facets in the OBJ model generated? Or how can I modify the code?

**Comment by AaronJackson** [comment]
There are few problems. First, this image is very tightly cropped, which may cause problems for the face and landmark detection (hence the strange behaviour around the jaw in the example you showed in the first message). Could you try padding the image prior to testing?

Second, the lighting is not great, but I suspect our method should be able to handle this. 

The obj file is dense, yes, because it is the extracted surface of a large 3D volume. It can be simplified using `reducepatch` in MATLAB, but if you are computing accuracy, a dense mesh should not be an issue.

If you are planning on comparing with our method for a publication, the only valid comparison which can be made is by using the MATLAB code, not the Python code or the online example (which uses the Python code). The results presented in our paper are using MATLAB code.

**Comment by linshisong** [comment]
I padding the image, and it had a good performance. Thank u.
