### ISSUE TITLE
What does the NME in you paper stand for?

### ISSUE THREAD

**Issue by crazySyaoran** [AaronJackson/vrn#130]

**Comment by AaronJackson** [comment]
It is explained under the section "Error Metric"  -  but it's Normalised Mean Error.

**Comment by crazySyaoran** [comment]
Yes I'm sorry I found it and closed the issue.
But I didn't find how do you change the hard (binary) result into a soft (real) predictions.
Did you give some detail in your paper?
Thanks

**Comment by AaronJackson** [comment]
During training, binary predictions are used (via Sigmoid activation function). Since it is Sigmoid, the values will not always be 1 or 0, they will be close to either of these numbers. If you have a surface extraction function which can uses non binary values, it can be used to improve detail (on better trained models) and result in a less blocky model. MATLAB's `isosurface` function supports these non binary values and hence the MATLAB version in this repo works better than the Python version.

**Comment by crazySyaoran** [comment]
Cool.
Thank you.
