### ISSUE TITLE
Runing code in CPU mode...

### ISSUE THREAD

**Issue by msiraj83** [AaronJackson/vrn#21]
I try to run the code.. For this purpose i prepare envrioment for GPU and run the code.. I got the out of memory error as shown in the screen shot..
![out_of_memory_error](https://user-images.githubusercontent.com/8863047/32555307-efe99410-c4ce-11e7-839c-677d81f6159d.png)
Than i try to run the code in CPU mood by setting the gpunum=-1.. When i run the code than i got another error... as show below....
![cpu_mode_error](https://user-images.githubusercontent.com/8863047/32555384-2652ed80-c4cf-11e7-8816-dded9ab328fa.png)

Can anybody help me how to run this code in CPU mode ???

Thanks

**Comment by AaronJackson** [comment]
Out of interest, what GPU are you using and how much video RAM does it have?

Unfortunately the face-alignment code cannot be run on the CPU as it was built using nngraph. Although, since the face-alignment code uses much less memory, perhaps you can run that on the GPU and then the reconstruction code on the CPU?

Hope that helps. Thanks for the screenshots, very useful.

**Comment by msiraj83** [comment]
@AaronJackson sorry for late reply... MY GPU is NVIDIA GEFORCE and 2GB... But i follow your instruction it work for now... is the texture code is not included???

Thanks

**Comment by AaronJackson** [comment]
There is an option in the run.m file which allows you to enable the vertex colouring
