### ISSUE TITLE
3d volumetric representation

### ISSUE THREAD

**Issue by wuneng** [AaronJackson/vrn#98]
Hi, AaronJackson
       I try to reimplement vrn. The 3d shape of face in 300W_LP often consists of face part, neck part and ear part. Unfortunately， the face part and neck part are useless.  The image demo in your paper only has face part. 
      Here are volumetric representation that generated by my code. There are still some difference between yours and mine, since my  volumetric representation consists of ear part and is not smooth.  I would  be appreciatedif you can share some information about how to generate the volumetric representation. By the way,  I would be happy to make the code public if  my reimplement is correct.

![1](https://user-images.githubusercontent.com/16924094/43458721-d8e812a0-94fd-11e8-93b9-302f251b05df.jpg)
![2](https://user-images.githubusercontent.com/16924094/43458757-f97c225e-94fd-11e8-9095-9306c7b2a882.jpg)

**Comment by AaronJackson** [comment]
One of the reasons we did not include the ears and neck is because they are not properly aligned from 3DDFA, so while you might be able to train a network to regress them, it is unlikely that the network will learn to regress the ear in the correct place.

From those images, it looks as thought the volume is only the skin. How did you voxelise these? Is it just the surface? The inside of the face should also be filled in with ones.

The easiest way to achieve a smooth surface is to produce the volume at double the actual scale, and then use cubic interpolation to halve the 3D size. This will produce smoother values on the edges. These smoother values will result in the isosurface also appearing smooth as long as the surface extraction algorithm supports that kind of representation.

**Comment by wuneng** [comment]
Yes, it is just the surface.Thanks for your help.
